### ISSUE TITLE
[nvm-iojs-latest] Cannot start, no sails

### ISSUE THREAD

**Issue by IanVS** [artificialio/docker-sails#11]
I'm trying to use nvm-iojs-latest in SANE, but getting the error message:

```
Cannot start container ee8a1d088eedcb4207730cfe35bca16557ef204c7d561766251bf53129b8d86c: exec: "sails": executable file not found in $PATH
```

This is the docker-compose.yml:

```
server:
  image: artificial/docker-sails:iojs-nvm-stable
  command: sails lift
  volumes:
    - server/:/server
  ports:
    - "1337:1337"
```

**Comment by kriswill** [comment]
It doesn't work for a few reasons.
1. nvm is initialized in the .bashrc, which is only executed in interactive shells.
2. even with nvm active, if I force an interactive shell, sails won't lift, because grunt isn't installed globally.

you can manually test this with:

``` sh
kris ~/src/oss/test-sane-docker 
→ docker run --rm -v `pwd`/server/:/server -it artificial/docker-sails:iojs-nvm-stable bash -i -c "sails lift"
```

if there is a way to disable the grunt-coffescript hooking that sails lift does, it will work.  In which case, you can simply modify the docker-compose.yml to include:

``` yml
server:
  image: artificial/docker-sails:iojs-nvm-stable
  command: bash -i -c "sails lift"
  volumes:
    - server/:/server
  ports:
    - "1337:1337"
```

keep in mind, the current build of the iojs-nvm-stable is built with iojs 1.5.1 and an older version of sails.  If I have some time tomorrow I'll see if I can update it.
